# Generated by Django 4.1.5 on 2023-01-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
            ],
        ),
    ]
