# Generated by Django 4.1.5 on 2023-03-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_prof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('dependencies', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('dependencies', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='prof',
            name='courses',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='prof',
            name='hard_times',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='prof',
            name='soft_times',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
