# Generated by Django 4.1.5 on 2023-03-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_course_course_data_prof_courses_prof_hard_times_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Course_Data',
        ),
        migrations.DeleteModel(
            name='Entries',
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='course',
            name='dependencies',
        ),
        migrations.RemoveField(
            model_name='prof',
            name='courses',
        ),
        migrations.AlterField(
            model_name='prof',
            name='hard_times',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='prof',
            name='soft_times',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='dependencies',
            field=models.ManyToManyField(to='pages.course', verbose_name='list of dependencies'),
        ),
        migrations.AddField(
            model_name='prof',
            name='courses',
            field=models.ManyToManyField(to='pages.course', verbose_name='list of eligible courses'),
        ),
    ]
